apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: auth9
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ3Bna2Q5MDYiLCJwYXNzd29yZCI6ImdocF9RRjVycjJ2cEc4RXNTSjg2ak9RTk1IdERYTW5sSnE0UWtIanciLCJhdXRoIjoiWjNCbmEyUTVNRFk2WjJod1gxRkdOWEp5TW5ad1J6aEZjMU5LT0RacVQxRk9UVWgwUkZoTmJteEtjVFJSYTBocWR3PT0ifX19
