apiVersion: v1
kind: Service
metadata:
  name: auth9-portal
  namespace: auth9
  labels:
    app.kubernetes.io/name: auth9-portal
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: auth9
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth9-portal
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
